import assert from "node:assert/strict";
import test from "node:test";

const EXPECTED_EXPORTS = [
  "DEFAULT_SALES_CREDIT_HOLD_DAYS",
  "DEFAULT_SALES_CREDIT_RISK_BUFFER_BPS",
  "DOCUMENT_VERIFICATION_STATUSES",
  "LEDGER_ENTRY_TYPES",
  "ORDER_STATUSES",
  "PAYOUT_RUN_STATUSES",
  "PAYOUT_TRANSFER_METHODS",
  "SALES_CREDIT_OFFSET_STATUSES",
  "SALES_CREDIT_PAYMENT_RISK_CLASSES",
  "SALES_CREDIT_PAYMENT_RISK_RATE_BPS",
  "SELLER_EU_STATUSES",
  "SELLER_STATUSES",
  "SELLER_VERIFICATION_STATUSES",
  "approvePayoutRun",
  "authorizeSalesCreditOffset",
  "backfillSellerOrderShadowChecks",
  "buildMarketplaceOrderSnapshot",
  "calculateSellerPayoutableLedgerBalance",
  "calculateSellerSalesCreditAvailability",
  "captureSalesCreditOffset",
  "createCheckoutOrder",
  "createCheckoutOrderPaymentIntent",
  "createConnectedAccountPayout",
  "createOrderRefund",
  "createPayoutRun",
  "createSellerAccountSession",
  "createSellerStripeAccount",
  "ensureSellerForVendor",
  "executePayoutRun",
  "executeWisePayoutRun",
  "getAdminSellerDetail",
  "getPayoutRunDetail",
  "getPlatformFeeBps",
  "getSellerPaymentsPageData",
  "getSellerPayoutVerificationState",
  "getSellerPayoutableLedgerBalance",
  "getSellerSalesCreditSummary",
  "getStripeClient",
  "getStripePublishableKey",
  "handleStripeWebhook",
  "inferShopifyOrderSalesCreditPaymentRisk",
  "listAdminSellerRows",
  "listPayoutRuns",
  "listSellerLedgerRepairCandidates",
  "markPayoutRunManuallyPaid",
  "markSalesCreditOffsetCheckoutCreated",
  "processShopifyDisputeSettlement",
  "processShopifyOrderCancelledSettlement",
  "processShopifyOrderPaidSettlement",
  "processShopifyRefundSettlement",
  "releaseSalesCreditOffset",
  "repairSellerNegativeLedgerBalance",
  "resetSellerStripeAccountForRecreate",
  "reverseSalesCreditOffsetForRefund",
  "syncSellerStripeAccountFromAccountUpdate",
  "syncWisePayoutRunStatus",
  "updateSellerStatus",
  "updateSellerVerification",
  "upsertSellerWiseRecipient",
].sort();

test("seller payments compatibility facade keeps its public API", async () => {
  const module = await import("../../app/services/sellerPayments.server.js");

  assert.deepEqual(Object.keys(module).sort(), EXPECTED_EXPORTS);
});
