# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eddd91eaa556b577d266009b6723851e"
name = "vendor-register"
application_url = "https://vendor-register-pbjl.onrender.com"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_products"

[auth]
redirect_urls = [ "https://vendor-register-pbjl.onrender.com/auth/callback" ]

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://vendor-register-pbjl.onrender.com/apps/vendors"
subpath = "vendors"
prefix = "apps"