export const MARKETPLACE_OPERATOR_ROLES = Object.freeze({
  ADMIN: "MARKETPLACE_ADMIN",
  FINANCE_PREPARER: "FINANCE_PREPARER",
  FINANCE_APPROVER: "FINANCE_APPROVER",
  FINANCE_EXECUTOR: "FINANCE_EXECUTOR",
  RELEASE_MANAGER: "RELEASE_MANAGER",
  INCIDENT_COMMANDER: "INCIDENT_COMMANDER",
  RECOVERY_APPROVER: "RECOVERY_APPROVER",
  COMPLIANCE_REVIEWER: "COMPLIANCE_REVIEWER",
});

const PRODUCTION_READINESS_ROLE_BY_INTENT = Object.freeze({
  record_operational_attestation:
    MARKETPLACE_OPERATOR_ROLES.COMPLIANCE_REVIEWER,
  activate_emergency_checkout_hold:
    MARKETPLACE_OPERATOR_ROLES.INCIDENT_COMMANDER,
  release_emergency_checkout_hold:
    MARKETPLACE_OPERATOR_ROLES.RECOVERY_APPROVER,
  activate_automated_email_hold:
    MARKETPLACE_OPERATOR_ROLES.INCIDENT_COMMANDER,
  release_automated_email_hold:
    MARKETPLACE_OPERATOR_ROLES.RECOVERY_APPROVER,
  activate_legal_email_hold:
    MARKETPLACE_OPERATOR_ROLES.INCIDENT_COMMANDER,
  release_legal_email_hold:
    MARKETPLACE_OPERATOR_ROLES.RECOVERY_APPROVER,
  activate_checkout_gate: MARKETPLACE_OPERATOR_ROLES.RELEASE_MANAGER,
  stage_checkout_validation: MARKETPLACE_OPERATOR_ROLES.RELEASE_MANAGER,
  activate_checkout_validation: MARKETPLACE_OPERATOR_ROLES.RELEASE_MANAGER,
});

export function resolveProductionReadinessOperatorRole(intent) {
  return (
    PRODUCTION_READINESS_ROLE_BY_INTENT[String(intent || "").trim()] ||
    MARKETPLACE_OPERATOR_ROLES.ADMIN
  );
}
