export const WITHDRAWAL_STATUSES = {
  REQUESTED: "REQUESTED",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  RETURN_REQUESTED: "RETURN_REQUESTED",
  RETURN_RECEIVED: "RETURN_RECEIVED",
  REFUND_PENDING: "REFUND_PENDING",
  REFUNDED: "REFUNDED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  ERROR: "ERROR",
};

export const WITHDRAWAL_ELIGIBILITY_STATUSES = {
  PENDING_REVIEW: "PENDING_REVIEW",
  ELIGIBLE: "ELIGIBLE",
  NON_EU_REVIEW: "NON_EU_REVIEW",
  DEADLINE_REVIEW: "DEADLINE_REVIEW",
  DEADLINE_EXPIRED: "DEADLINE_EXPIRED",
  ORDER_NOT_FOUND_REVIEW: "ORDER_NOT_FOUND_REVIEW",
  EMAIL_MISMATCH_REVIEW: "EMAIL_MISMATCH_REVIEW",
  EXEMPTION_REVIEW: "EXEMPTION_REVIEW",
  VALUE_REDUCTION_REVIEW: "VALUE_REDUCTION_REVIEW",
};

export const WITHDRAWAL_STATUS_LABELS = {
  [WITHDRAWAL_STATUSES.REQUESTED]: "申請受付",
  [WITHDRAWAL_STATUSES.ACKNOWLEDGED]: "受付メール送信済み",
  [WITHDRAWAL_STATUSES.UNDER_REVIEW]: "確認中",
  [WITHDRAWAL_STATUSES.APPROVED]: "承認済み",
  [WITHDRAWAL_STATUSES.RETURN_REQUESTED]: "返送待ち",
  [WITHDRAWAL_STATUSES.RETURN_RECEIVED]: "返送確認済み",
  [WITHDRAWAL_STATUSES.REFUND_PENDING]: "返金準備中",
  [WITHDRAWAL_STATUSES.REFUNDED]: "返金済み",
  [WITHDRAWAL_STATUSES.CANCELLED]: "注文キャンセル済み",
  [WITHDRAWAL_STATUSES.REJECTED]: "却下",
  [WITHDRAWAL_STATUSES.EXPIRED]: "期限切れ",
  [WITHDRAWAL_STATUSES.ERROR]: "要確認",
};

export const WITHDRAWAL_ELIGIBILITY_LABELS = {
  [WITHDRAWAL_ELIGIBILITY_STATUSES.PENDING_REVIEW]: "確認待ち",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.ELIGIBLE]: "対象候補",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.NON_EU_REVIEW]: "EU外の可能性",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.DEADLINE_REVIEW]: "期限確認",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.DEADLINE_EXPIRED]: "期限超過の可能性",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.ORDER_NOT_FOUND_REVIEW]: "注文確認待ち",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.EMAIL_MISMATCH_REVIEW]: "メール照合待ち",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.EXEMPTION_REVIEW]: "例外確認",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.VALUE_REDUCTION_REVIEW]: "減額確認",
};

export const WITHDRAWAL_STATUS_TONES = {
  [WITHDRAWAL_STATUSES.REQUESTED]: "info",
  [WITHDRAWAL_STATUSES.ACKNOWLEDGED]: "info",
  [WITHDRAWAL_STATUSES.UNDER_REVIEW]: "warning",
  [WITHDRAWAL_STATUSES.APPROVED]: "success",
  [WITHDRAWAL_STATUSES.RETURN_REQUESTED]: "warning",
  [WITHDRAWAL_STATUSES.RETURN_RECEIVED]: "success",
  [WITHDRAWAL_STATUSES.REFUND_PENDING]: "warning",
  [WITHDRAWAL_STATUSES.REFUNDED]: "success",
  [WITHDRAWAL_STATUSES.CANCELLED]: "success",
  [WITHDRAWAL_STATUSES.REJECTED]: "danger",
  [WITHDRAWAL_STATUSES.EXPIRED]: "danger",
  [WITHDRAWAL_STATUSES.ERROR]: "danger",
};

export const WITHDRAWAL_ELIGIBILITY_TONES = {
  [WITHDRAWAL_ELIGIBILITY_STATUSES.PENDING_REVIEW]: "warning",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.ELIGIBLE]: "success",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.NON_EU_REVIEW]: "warning",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.DEADLINE_REVIEW]: "warning",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.DEADLINE_EXPIRED]: "danger",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.ORDER_NOT_FOUND_REVIEW]: "warning",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.EMAIL_MISMATCH_REVIEW]: "warning",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.EXEMPTION_REVIEW]: "warning",
  [WITHDRAWAL_ELIGIBILITY_STATUSES.VALUE_REDUCTION_REVIEW]: "warning",
};

export function getWithdrawalStatusLabel(status) {
  return WITHDRAWAL_STATUS_LABELS[status] || status || "-";
}

export function getWithdrawalEligibilityLabel(status) {
  return WITHDRAWAL_ELIGIBILITY_LABELS[status] || status || "-";
}

export function getWithdrawalStatusTone(status) {
  return WITHDRAWAL_STATUS_TONES[status] || "neutral";
}

export function getWithdrawalEligibilityTone(status) {
  return WITHDRAWAL_ELIGIBILITY_TONES[status] || "neutral";
}
