export const RETURN_DISPOSITIONS = Object.freeze({
  RETURN_REQUIRED: "RETURN_REQUIRED",
  RETURN_NOT_REQUIRED: "RETURN_NOT_REQUIRED",
  COLLECTION_REQUIRED: "COLLECTION_REQUIRED",
  NON_PHYSICAL: "NON_PHYSICAL",
  EXEMPTION_REVIEW: "EXEMPTION_REVIEW"
});
