query CartValidationsGenerateRunInput {
  shop {
    localTime {
      date
    }
    operationalPurchaseControl: metafield(
      namespace: "$app"
      key: "operational_purchase_control"
    ) {
      value
    }
    watchdogPurchaseStop: metafield(
      namespace: "vendor_register_watchdog"
      key: "purchase_stop"
    ) {
      value
    }
    komojuLimitedLaunchControl: metafield(
      namespace: "$app"
      key: "komoju_limited_launch_control"
    ) {
      value
    }
  }
  cart {
    cost {
      totalAmount {
        amount
        currencyCode
      }
    }
    lines {
      quantity
      merchandise {
        ... on ProductVariant {
          id
          product {
            id
            marketplaceCheckoutPolicy: metafield(
              namespace: "$app"
              key: "marketplace_checkout_policy"
            ) {
              value
            }
            saleEligibilityProjection: metafield(
              namespace: "$app"
              key: "sale_eligibility_projection"
            ) {
              value
            }
          }
        }
      }
    }
  }
}
